import type { Metadata } from "next";
import { Inknut_Antiqua } from "next/font/google";
import { Jost } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const jost = Jost({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-jost",
});

const inknut = Inknut_Antiqua({
  subsets: ["latin"],
  weight: ["400", "700", "500", "300"],
  variable: "--font-inknut",
});
 

export const metadata: Metadata = {
  title: "Notez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${jost.variable} ${inknut.variable} font-mono `}>
        {/* ✅ Place ThemeProvider here */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
